# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/linuxbrew/.linuxbrew/Cellar/cmake/3.25.2/bin/cmake

# The command to remove a file.
RM = /home/linuxbrew/.linuxbrew/Cellar/cmake/3.25.2/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mikoaj/Projects/MatrixMult

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mikoaj/Projects/MatrixMult

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/home/linuxbrew/.linuxbrew/Cellar/cmake/3.25.2/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/linuxbrew/.linuxbrew/Cellar/cmake/3.25.2/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mikoaj/Projects/MatrixMult/CMakeFiles /home/mikoaj/Projects/MatrixMult//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mikoaj/Projects/MatrixMult/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named benchmarkMult

# Build rule for target.
benchmarkMult: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 benchmarkMult
.PHONY : benchmarkMult

# fast build rule for target.
benchmarkMult/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmarkMult.dir/build.make CMakeFiles/benchmarkMult.dir/build
.PHONY : benchmarkMult/fast

#=============================================================================
# Target rules for targets named compilation_complete

# Build rule for target.
compilation_complete: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 compilation_complete
.PHONY : compilation_complete

# fast build rule for target.
compilation_complete/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compilation_complete.dir/build.make CMakeFiles/compilation_complete.dir/build
.PHONY : compilation_complete/fast

#=============================================================================
# Target rules for targets named run_all

# Build rule for target.
run_all: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run_all
.PHONY : run_all

# fast build rule for target.
run_all/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_all.dir/build.make CMakeFiles/run_all.dir/build
.PHONY : run_all/fast

multBenchmark.o: multBenchmark.cpp.o
.PHONY : multBenchmark.o

# target to build an object file
multBenchmark.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmarkMult.dir/build.make CMakeFiles/benchmarkMult.dir/multBenchmark.cpp.o
.PHONY : multBenchmark.cpp.o

multBenchmark.i: multBenchmark.cpp.i
.PHONY : multBenchmark.i

# target to preprocess a source file
multBenchmark.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmarkMult.dir/build.make CMakeFiles/benchmarkMult.dir/multBenchmark.cpp.i
.PHONY : multBenchmark.cpp.i

multBenchmark.s: multBenchmark.cpp.s
.PHONY : multBenchmark.s

# target to generate assembly for a file
multBenchmark.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmarkMult.dir/build.make CMakeFiles/benchmarkMult.dir/multBenchmark.cpp.s
.PHONY : multBenchmark.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... compilation_complete"
	@echo "... run_all"
	@echo "... benchmarkMult"
	@echo "... multBenchmark.o"
	@echo "... multBenchmark.i"
	@echo "... multBenchmark.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

